#cloud-config
runcmd:
  - echo 'Hello, World!' > /var/tmp/hello-world.txt
  - sudo apt install -y snapd ufw
  - sudo snap install microk8s --classic
  - sudo apt install ufw
  - ufw allow in on cni0 && sudo ufw allow out on cni0
  - ufw default allow routed
  - |
    cat > /etc/rc.local <<EOF
    #!/bin/bash

    apparmor_parser --replace /var/lib/snapd/apparmor/profiles/snap.microk8s.*
    exit 0
    EOF
  - chmod +x /etc/rc.local
  - microk8s start
  - microk8s status
  - microk8s enable ingress
apt_update: true
apt_upgrade: true
package_update: true
package_upgrade: true
package_reboot_if_required: false
