name: "filerun"

services:
  db:
    image: "mariadb:12.2"
    environment:
      MARIADB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_USER: "filerun"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "filerun"
      MARIADB_AUTO_UPGRADE: 1
    networks:
      - default
    volumes:
      - "${CONFIG_FOLDER}/filerun/db:/var/lib/mysql"
  web:
    image: "filerun/filerun"
    user: "1001:1001"
    environment:
      FR_DB_HOST: "db"
      FR_DB_PORT: "3306"
      FR_DB_NAME: "filerun"
      FR_DB_USER: "filerun"
      FR_DB_PASS: "${DB_PASSWORD}"
    networks:
      - default
      - shared
    depends_on:
      - "db"
    links:
      - "db:db"
    expose:
      - "80"
    volumes:
      - "${FILES_FOLDER}/filerun/html:/var/www/html"
      - "${FILES_FOLDER}/filerun/user-files:/user-files"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.photos.rule=Host(`filerun.tqid.dev`)"
      - "traefik.http.routers.photos.entrypoints=web"


networks:
  default:
  shared:
    name: docker_default
    external: true