version: "3.8"

services:
  prometheus:
    image: "prom/prometheus:latest"
    restart: "always"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    volumes:
      - "../etc/prometheus.yml:/etc/prometheus/prometheus.yml"
      - "prometheus:/prometheus"
    expose:
      - "9090"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prom.rule=Host(`prometheus.tqid.dev`)"
      - "traefik.http.routers.prom.entrypoints=web"


volumes:
  prometheus:

networks:
  default: