version: "3.8"

services:
  budge:
    image: "thequeenisdead/budge:latest"
    restart: "always"
    environment:
      BUDGE_BOLT_PATH: "/var/lib/budge"
    volumes:
      - "budge:/var/lib/budge"
    expose:
      - "1337"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.budge.rule=Host(`budge.tqid.dev`)"
      - "traefik.http.routers.budge.entrypoints=web"

  chat:
    image: "thequeenisdead/go-chat:latest"
    restart: "always"
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chat.rule=Host(`chat.tqid.dev`)"
      - "traefik.http.routers.chat.entrypoints=web"

volumes:
  budge:

networks:
  default: