---
- name: "Copy docker-compose config to server"
  ansible.builtin.copy:
    src: "{{ compose_directory }}/"
    dest: /compose/
    owner: pi
    group: pi

- name: "Bring up Compose service stack"
  community.docker.docker_compose:
    project_src: /compose
