version: '3.8'

# All services meant to be run on pi.local domain.

services:

  # https://traefik.io/
  traefik:
    image: "traefik:v2.6"
    container_name: "traefik"
    hostname: "traefik"
    restart: always
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    labels:
      # https://stackoverflow.com/questions/61572512/expose-traefik-dashboard-to-subdomain
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_FQDN}`)"
      - "traefik.http.routers.dashboard.entrypoints=web"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks: # Allow traefik to view public and private facing applications.
      - internal
      - external

  # https://pi-hole.net/
  # https://github.com/pi-hole/docker-pi-hole/blob/master/docker_run.sh
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole
    restart: always
    # Requires 53 to be free, this mandates extra steps on Ubuntu by default
    # https://codepre.com/ubuntu-how-to-release-port-53-used-by-systemd-resolved.html
    # Also requires 53 to be bound to a specific address in order to preserve name resolution in other containers
    # https://discourse.pi-hole.net/t/solve-dns-resolution-in-other-containers-when-using-docker-pihole/31413
    ports:
      - "53:53/tcp"
      - "${INGRESS_IP}:53:53/udp"
    dns:
      - 127.0.0.1
      - 9.9.9.9
    environment:
      # https://github.com/pi-hole/docker-pi-hole#environment-variables
      TZ: "Pacific/Auckland"
      WEBPASSWORD: 'PASSWORD'
      PIHOLE_DNS_: 9.9.9.9;149.112.112.112;1.1.1.1
      DNSSEC: 'true'
      ServerIP: 192.168.0.169 # Actual server IP. Matches DHCP conf file IP
      VIRTUAL_HOST: "${PIHOLE_FQDN}"
      CORS_HOSTS: "${HOMER_FQDN}"
      DNSMASQ_LISTENING: all
      DHCP_ACTIVE: 'true'
      WEBTHEME: default-dark
      PIHOLE_DOMAIN: lan
    volumes:
      - '/services/pihole/pihole:/etc/pihole/'
      - '/services/pihole/dnsmasq.d:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    networks:
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`${PIHOLE_FQDN}`)"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      - "traefik.http.routers.pihole.entrypoints=web"

  speedtest:
    image: lscr.io/linuxserver/librespeed
    container_name: speedtest
    hostname: speedtest
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Pacific/Auckland
      PASSWORD: testing123
    expose:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.speedtest.rule=Host(`${SPEEDTEST_FQDN}`)"
      - "traefik.http.routers.speedtest.entrypoints=web"
    networks:
      - internal

  homer:
    image: b4bz/homer:latest
    container_name: homer
    hostname: homer
    restart: unless-stopped
    volumes:
      - '/compose/homer.yml:/www/assets/config.yml'
    expose:
      - 8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homer.rule=Host(`${HOMER_FQDN}`)"
      - "traefik.http.routers.homer.entrypoints=web"
    networks:
      - internal

  radarr:
    restart: unless-stopped
    image: ghcr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - radarr_config_volume:/config
      - media_volume:/media
    expose:
      - 7878
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`${RADARR_FQDN}`)"
      - "traefik.http.routers.radarr.entrypoints=web"
    networks:
      - internal

  sonarr:
    restart: unless-stopped
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - sonarr_config_volume:/config
      - media_volume:/media
    expose:
      - 8989
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`${SONARR_FQDN}`)"
      - "traefik.http.routers.sonarr.entrypoints=web"
    networks:
      - internal

  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    hostname: prowlarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - prowlarr_config_volume:/config
    expose:
      - 9696
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.rule=Host(`${PROWLARR_FQDN}`)"
      - "traefik.http.routers.prowlarr.entrypoints=web"
    networks:
      - internal

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    hostname: jellyfin
    restart: unless-stopped
    environment:
      - TZ=Pacific/Auckland
    volumes:
      - jellyfin_volume:/config
      - jellyfin_volume:/cache
      - media_volume:/media
    expose:
      - 80
      - 8096
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`${JELLYFIN_FQDN}`)"
      - "traefik.http.routers.jellyfin.entrypoints=web"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
    networks:
      - internal

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    hostname: plex
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - plex_config_volume:/config
      - media_volume:/media
    expose:
      - 32400
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex.rule=Host(`${PLEX_FQDN}`)"
      - "traefik.http.routers.plex.entrypoints=web"
      - "traefik.http.services.plex.loadbalancer.server.port=32400"
    networks:
      - internal

  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    hostname: transmission
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    volumes:
      - transmission_config_volume:/config
      - media_volume:/downloads
    expose:
      - 9091 # Web UI port
      - 51413 # Torrent port (TCP)
      - 51413/udp # Torrent port (UDP)
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.rule=Host(`${TRANSMISSION_FQDN}`)"
      - "traefik.http.routers.transmission.entrypoints=web"
    networks:
      - internal

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    hostname: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    expose:
      - 9100
    networks:
      - internal

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    hostname: prometheus
    restart: unless-stopped
    volumes:
      - /compose/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_volume:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prom.rule=Host(`${PROMETHEUS_FQDN}`)"
      - "traefik.http.routers.prom.entrypoints=web"
    expose:
      - 9090
    networks:
      - internal

  grafana:
    image: grafana/grafana
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    expose:
      - 3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`${GRAFANA_FQDN}`)"
      - "traefik.http.routers.grafana.entrypoints=web"
    volumes:
      - grafana_volume:/var/lib/grafana:rw
    networks:
      - internal

volumes:
  # Service config volumes
  ## Misc
  prometheus_volume:
  jellyfin_volume:
  grafana_volume:
  transmission_config_volume:
  plex_config_volume:
  ## Arr config
  jackett_config_volume:
  radarr_config_volume:
  sonarr_config_volume:
  prowlarr_config_volume:
  # Media volumes - Ext HDD
  # Volume from Device: https://serverfault.com/questions/1053820/can-docker-volumes-be-mounted-from-a-device-instead-of-bind-mounting-a-directory
  # Escape option strings: https://docs.docker.com/storage/volumes/#choose-the--v-or---mount-flag
  # NTFS mount options: https://www.commandlinux.com/man-page/man8/mount.ntfs.8.html
  media_volume:
    driver: local
    driver_opts:
      type: ntfs
      device: /dev/disk/by-uuid/5668681D6867FA5F
      o: "uid=1000,gid=1000,umask=000,fmask=000,dmask=000"

networks:
  internal:
  external: