- name: "Home Infrastructure Setup"

  hosts: rpi

  vars:
    pip_package: python3-pip

  roles:
    - geerlingguy.pip
    - geerlingguy.docker_arm

  gather_facts: false
  tasks:

    - name: "Debug config.json post register"
      ansible.builtin.debug:
        var: config
      delegate_to: localhost

    - name: "Write FQDN to Docker config file"
      ansible.builtin.lineinfile:
        path: ../compose/.env
        search_string: "{{ item.key | capitalize }}_FQDN"
        state: present
        line: "{{ item.key | upper }}_FQDN={{item.value}}.{{ config.domain }}"
      loop: "{{ lookup('dict', config.subdomains) }}"
      delegate_to: localhost

    - name: "Create compose directory"
      file:
        path: /compose
        state: directory

    - name: "Copy docker-compose config to server"
      ansible.builtin.copy:
        src: ../compose/
        dest: /compose/
        owner: pi
        group: pi

    - name: "Bring up Compose service stack"
      community.docker.docker_compose:
        project_src: /compose

    - name: "Provision internal DNS on PiHole via Terraform"
      delegate_to: localhost
      community.general.terraform:
        project_path: ../terraform
        state: present
