- name: "Home Infrastructure Setup"

  hosts: rpi

  vars:
    pip_package: python3-pip
    compose_directory: "{{ playbook_dir }}/../compose"
    terraform_directory: "{{ playbook_dir }}/../terraform"

  gather_facts: false

  tasks:
    - name: "Initialise config"
      include_tasks:
        file: ./tasks/config.yml
        apply:
          tags:
            - config

    - name: "Configure ARM Host"
      include_tasks:
        file: ./tasks/raspberrypi.yml
        apply:
          tags:
            - host
            - pi

    - name: "Deploy docker-compose"
      include_tasks:
        file: ./tasks/compose.yml
        apply:
          tags:
            - docker
            - app
            - compose

    - name: "Terraform internal DNS"
      include_tasks:
        file: ./tasks/terraform.yml
        apply:
          tags:
            - terraform
            - dns
            - pihole
