- name: "Home Infrastructure Setup"

  hosts: rpi

  vars:
    pip_package: python3-pip

  roles:
    - geerlingguy.pip
    - geerlingguy.docker_arm

  gather_facts: false
  tasks:
    - name: "Create compose directory"
      file:
        path: /compose
        state: directory

    - name: "Copy docker-compose.yml to server"
      ansible.builtin.copy:
        src: ../compose/docker-compose.yml
        dest: /compose/docker-compose.yml
        owner: pi
        group: pi

    - name: "Copy homer.yml to server"
      ansible.builtin.copy:
        src: ../compose/homer.yml
        dest: /compose/homer.yml
        owner: pi
        group: pi

    - name: "Copy prometheus.yml to server"
      ansible.builtin.copy:
        src: ../compose/prometheus.yml
        dest: /compose/prometheus.yml
        owner: pi
        group: pi

    - name: "Bring up Compose service stack"
      community.docker.docker_compose:
        project_src: /compose

    - name: "Provision internal DNS on PiHole via Terraform"
      delegate_to: localhost
      community.general.terraform:
        project_path: ../terraform
        state: present
