- name: "Home Infrastructure Setup"

  hosts: nuc

  vars:
    pip_package: python3-pip
    compose_directory: "{{ playbook_dir }}/../compose"
    terraform_directory: "{{ playbook_dir }}/../terraform"

  gather_facts: false

  tasks:
    - name: "ping"
      ping:

    - name: "Install KVM"
      include_tasks:
        file: ./tasks/virt.yml
        apply:
          tags:
            - deps
      tags:
        - always

    - name: "Configure VM's"
      include_tasks:
        file: ./tasks/vm.yml
        apply:
          tags:
            - vm
      tags:
        - always

#
#    - name: "Configure ARM Host"
#      include_tasks:
#        file: ./tasks/raspberrypi.yml
#        apply:
#          tags:
#            - host
#            - pi
#      tags:
#        - always
#
#    - name: "Deploy docker-compose"
#      include_tasks:
#        file: ./tasks/compose.yml
#        apply:
#          tags:
#            - docker
#            - app
#            - compose
#      tags:
#        - always
#
#    - name: "Terraform internal DNS"
#      include_tasks:
#        file: ./tasks/terraform.yml
#        apply:
#          tags:
#            - terraform
#            - dns
#            - pihole
#      tags:
#        - always
