name: "FileRun"

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/filerun.yml
      - docker/filerun.yml
    branches:
      - main

jobs:
  safe:
    runs-on: self-hosted
    env:
      CONFIG_FOLDER: "/mnt/unitek/config"
      FILES_FOLDER: "/mnt/unitek/files"
      DB_PASSSWORD: ${{ secrets.FILERUN_DB_PASSWORD }}
      DB_ROOT_PASSWORD: ${{ secrets.FILERUN_DB_ROOT_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - run: docker compose -f docker/filerun.yml up --wait
