name: "Grafana"

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/grafana.yml
      - docker/grafana.yml
    branches:
      - main

jobs:
  grafana:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: docker compose -f docker/grafana.yml up --wait
