name: "Node Exporter"

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/node.yml
      - docker/node.yml
    branches:
      - main

jobs:
  node:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: docker compose -f docker/node.yml up --wait
