on:
  push:
    paths:
      - .github/workflows/node.yml
      - docker/node.yml
    branches:
      - main
      - 2024

jobs:
  node:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: docker etc -f docker/node.yml up --wait
