on:
  push:
    paths:
      - .github/workflows/prometheus.yml
      - docker/prometheus.yml
    branches:
      - main
      - 2024

jobs:
  prometheus:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: docker etc -f docker/prometheus.yml up --wait
