on:
  push:
    paths:
      - .github/workflows/prometheus.yml
      - docker/prometheus.yml
      - etc/prometheus.yml
    branches:
      - main

jobs:
  prometheus:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: docker compose -f docker/prometheus.yml up --wait
