on:
  push:
    paths:
      - .github/workflows/s3fs.yml
      - docker/s3fs.yml
    branches:
      - main

jobs:
  s3fs:
    runs-on: self-hosted
    env:
      AWS_S3_ACCESS_KEY_ID: ${{ secrets.aws_s3_access_key_id }}
      AWS_S3_SECRET_ACCESS_KEY: ${{ secrets.aws_s3_secret_access_key }}
    steps:
      - uses: actions/checkout@v4
      - run: docker compose -f docker/s3fs.yml up --wait
