on:
  push:
    branches:
      - 2024

jobs:

  traefik:
    defaults:
      run:
        working-directory: docker
    runs-on: self-hosted
    steps:
      - run: docker ps

      - uses: actions/checkout@v4

      - run: docker compose up --wait -f traefik.yml
